### ISSUE TITLE
Crash if a directory name is passed as game

### ISSUE THREAD

**Issue by mcejp** [heuripedes/sdlarch#13]
It appears that -1 is assigned as file size at https://github.com/heuripedes/sdlarch/blob/10a9ffda2590d84123c5ab37bfb0b4f308c758e6/sdlarch.c#L700

A crash follows after trying to allocate a buffer of `(size_t)-1` bytes

**Comment by heuripedes** [comment]
Fixed by 4411ba5a469823fe4321f84f558894e9b550ad89. The program will now check the return from `SDL_RWsize` before allocating.
