### ISSUE TITLE
Support for non-emulator cores / RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME

### ISSUE THREAD

**Issue by mcejp** [heuripedes/sdlarch#14]
A libretro core can declare
```c
bool no_game = true;
env_cb(RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME, &no_game);
```

In that case, it should be possible to run the core without specifying a game.

However, sdlarch refuses to launch with just one argument (`usage: sdlarch <core> <game>`)

**Comment by heuripedes** [comment]
Fixed in 8a9b082775e24e25ce48286da7d2ae4352c28397
