### ISSUE TITLE
NDI idea

### ISSUE THREAD

**Issue by humbertodias** [heuripedes/sdlarch#16]
First of all. Great work.
Wait you seems to understand portuguese :)
So, here it goes:
Vi que possui dois projetos: nanoarch e sdlarch que são similares.
A ideia seria, abstrair a saída gráfica e sonora utilizando [NDI](https://en.wikipedia.org/wiki/Network_Device_Interface).
Já que existe o núcleo [libretro-ffmeg ](https://github.com/libretro/RetroArch/tree/master/cores/libretro-ffmpeg) que poderia ser compilado com suporte a [Network Device Interface](https://lauri.anteploon.com/2019/01/compiling-ffmpeg-with-ndi-support-on-linux/).
Com isso, "em teoria", poderia fazer streaming de qualquer jogo suportado por libretro para qualquer dispositivo sem a necessidade da camada gráfica/sonora em sdl2 ou glfw. Imagino que para o joystick ainda seria necessário.
Os clientes [VLC](https://www.phoronix.com/scan.php?page=news_item&px=libndi-NDI-Video-Stream) e [OBS](https://obsproject.com/forum/resources/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.528/) parecem já suportar.
Tive essa ideia, enquanto ouvia o criador [Andrew](https://www.retrorgb.com/eposvox-interviews-the-creator-of-ndi.html) comentando sobre o protocolo.
Enfim, vou fazer um fork do projeto e tentar implementar também.

**Comment by heuripedes** [comment]
Oi Humberto,

Não sei direito como esse NDI funciona, mas é bem interessante. Quanto a tirar a camada gráfica, acho que isso limitaria o programa a apenas os cores que geram quadros na memória, já que para cores que usam OpenGL/Vulkan/DirectX etc ainda seria necessário alguma biblioteca de carregamento e abstração dessas APIs.

Se o NDI suportar um tráfego bidirecional adicional o input poderia ser enviado para o servidor utilizando esse fluxo. Um cliente especial faria a leitura do dispositivo e exibição da tela, os outros tipo OBS ignorariam o fluxo adicional e simplesmente lidariam com audio e vídeo.

Eu imagino que algo assim vai complicar bastante o sdlarch/nanoarch e esse é um projeto que eu fiz pra ficar simples mesmo. Como algo educacional, sabe? Por esse motivo provavelmente não vou aceitar uma PR que implemente suporte a NDI, mas não deixe isso te impedir de trabalhar no seu fork.

Falou!
