### ISSUE TITLE
OpenGL Sample

### ISSUE THREAD

**Issue by RobLoach** [heuripedes/sdlarch#2]
When running through the following OpenGL sample:
https://github.com/libretro/libretro-samples/tree/master/video/opengl/libretro_test_gl_fixedfunction

I get the following:
```
Failed to create OpenGL context: Could not create GL context: BadMatch (invalid parameter attributes)
```

It works through RetroArch though, know what I'm missing?

**Comment by heuripedes** [comment]
Fixed it in https://github.com/heuripedes/sdlarch/commit/b68096c0c62ec971b4fb9682bccd7a0587206c3d.
Core might still not load because the shaders require GLSL 1.5 (aka 150) and some drivers might complain about using it in an older GL version.

**Comment by RobLoach** [comment]
Ah, that makes sense. I'll give it another test later on! Thanks a lot.

**Comment by RobLoach** [comment]
You're right:

```
Failed to compile vertex shader: 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES
```

I am on a laptop with integrated graphics, so I don't expect all things to work. Nice job on getting this going! :+1:
